plugins:
    - "prettier-plugin-go-template"
proseWrap: always
printWidth: 80
useTabs: true
tabWidth: 4
overrides:
    - files: "**/*.yaml"
      options:
          tabWidth: 2
          useTabs: false
          parser: yaml
    - files: "**/*.md"
      options:
          tabWidth: 2
          useTabs: false
          parser: markdown
    - files: "**/*.html"
      options:
          parser: "go-template"
