# https://taskfile.dev

version: "3"
vars:
  GREETING: Hello, World!
tasks:
  dev:
    cmd: docker compose -f docker-compose.dev.yml up
  serve:
    cmd: hugo server serve --buildDrafts --disableFastRender --renderToMemory --watch
#    cmd: fd . | entr -r go run ./cmd
#    sources:
#      - data/posts/*.md
#      - portfolio/**/*.go
#      - ./**.go
#      - themes/**
#    silent: true
  test:
    cmd: go test ./... "{{.CLI_ARGS}}"
    sources:
      - data/posts/*.md
      - portfolio/**/*.go
      - ./**.go
      - themes/**
    silent: true
    watch: true
