FROM golang:1.25-alpine

WORKDIR /workspace

# Install hot-reload tool (optional, can be removed if not needed)
RUN go install github.com/air-verse/air@latest

# Install dependencies
RUN apk add --no-cache curl git

COPY go.mod go.sum ./
RUN go mod download

# The actual command is provided by docker-compose
# CMD ["go", "run", "./cmd"]
CMD ["air"]
